# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-14 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeschool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_information',
            name='description',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='basic_information',
            name='titre',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='chapitreclasse',
            name='titre',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='classe',
            name='tags',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='creation_chapitre',
            name='description',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='creation_chapitre',
            name='titre',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='creation_td',
            name='titre',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='titre',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='travauxdirigesclasse',
            name='titre',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
