from django.conf.urls import url
from .views import *
urlpatterns = [
    url(r'^chapitres/by/matiere/$', get_chapitres_by_matiere, name='chapitres-by-matieres'),
    url(r'^chapitre/all/info/$', get_chapitre_all_info, name='chapitre-all-info'),
    url(r'^questions/by/chapitre/$', get_questions_by_chapitre, name='questions-by-chapitre'),
    url(r'^questions/supprimer/$', supprimer_une_question, name='supprimer-question'),
    url(r'^question/create/configuration/$', save_configuration_of_question, name='question-create-configuration'),
    url(r'^proposition/create/$', save_proposition, name='proposition-create'),
    url(r'^proposition/supprimer/$', supprimer_proposition, name='proposition-supprimer'),
    url(r'^profile/save/$', profile_save, name='profile-save'),
    url(r'^creer/devoir/$', create_devoir, name='create-devoir'),
    url(r'^quizz/detail/(?P<idQuizz>\w+)/$', get_quizz, name='quizz-detail'),
    url(r'^quizz/detail/correction/(?P<idQuizz>\w+)/$', get_quizz_correction, name='quizz-detail-correction'),
    url(r'^devoir/soumettre/$', soumettre_reponses_devoir, name='devoir-soumettre'),
    url(r'^devoir/save/(?P<classeID>\w+)/$', save_devoir, name='devoir-save'),
    url(r'^demande/inscription/$', inscription, name='inscription'),
    url(r'^eleve/information/$', get_eleve, name='eleve-information'),
    url(r'^classe/list/$', get_cours_list, name='classe-list'),
    url(r'^classes/$', categories, name='classes'),
    url(r'^classe/devoirs/(?P<classeID>\w+)/$', get_classe_devoir, name='classe-devoirs'),
    url(r'^classes/search/$', get_filtre, name='classes-search'),
    url(r'^classe/annonces/$', get_annonces, name='classe-annonces'),
    url(r'^assignment/top/information/$', assignment_top, name='assignment-top'),
    url(r'^question/nouvelle/$', refresh_nouvelle_question_form, name='question-nouvelle'),
    url(r'^groupe/classes/$', get_classe_of_groupe, name='goupe-classes'),
    url(r'^classe/chapitres/$', get_chapitres_of_classe, name='classe-chapitres'),
    url(r'^classe/chapitres/more/$', get_chapitres_of_classe_more_info, name='classe-chapitres-more'),
    url(r'^classe/chapitre/save/$', save_chapitre_classe, name='classe-chapitre-save'),
    url(r'^chapitre/questions/$', get_questions_of_chapitre, name='chapitre-questions'),
    url(r'^devoir/corrige/(?P<devoirID>\w+)/$', afficher_reponses_devoir, name='devoir-corrige'),
    url(r'^devoir/supprimer/(?P<devoirID>\w+)/(?P<classeID>\w+)/$', delete_devoir, name='devoir-supprimer'),
    url(r'^chapitre/posts/$', get_post_chapitre_list, name='chapitre-post'),
    url(r'^comment/post/$', envoyer_un_commentaire, name='chapitre-post'),
    url(r'^verifier/visiteur/$', verifier_inscrit_ou_enseignant, name='verifier-visiteur'),
    url(r'^copies/eleve/$', copies_eleve_by_devoir, name='copies-eleve'),
    url(r'^copie/eleve/$', copie_eleve_of_devoir, name='copie-eleve-devoir'),
    url(r'^copies/eleve/classe/$', copies_eleves_classe, name='copies-eleve-classe'),

]