from django.conf.urls import url, include
from homeschool import views
from homeschool.views import callback_wecashup_test, webhook_wecashup_test

urlpatterns = [
    url(r'^api/', include('homeschool.api.urls')),
    url(r'^api/mobile/', include('homeschool.api.mobile.urls')),
    url(r'^$', views.home, name="accueilMedecine"),
    url(r'^profile/$', views.profile, name="profile"),
    url(r'^cours/$', views.list_cours, name="list-cours"),
    url(r'^login/$', views.login, name="login"),
    url(r'^enregistrer/$', views.enregistrer, name="enregistrer"),
    url(r'^$', views.home, name="home"),
    url(r'^quizz/(?P<devoirID>\w+)/$', views.quizz, name="quizz"),
    url(r'^quizz/demo/(?P<devoirID>\w+)/$', views.quizz_demo, name="quizz-demo"),
    url(r'^categories/$', views.categories, name="categories"),
    url(r'^asignment_after_submit/$', views.assignment_after_submit, name="asignment_after_submit"),
    url(r'^asignment_list/$', views.assignment_list, name="asignment_list"),
    url(r'^asignment_marking/$', views.assignment_marking, name="asignment_marking"),
    url(r'^asignment_received/$', views.assignment_received, name="asignment_received"),
    url(r'^asignment_submit/$', views.assignment_submit, name="asignment_submit"),
    url(r'^account_devoir/$', views.account_devoir, name="account_devoir"),
    url(r'^account_messagerie/$', views.account_messagerie, name="account_messagerie"),
    url(r'^account_apprentissage/$', views.account_apprentissage, name="account_apprentissage"),
    url(r'^account_profil_invite/$', views.account_profil_invite, name="account_profil_invite"),
    url(r'^account_profil_titulaire/$', views.account_profil_titulaire, name="account_profil_titulaire"),
    url(r'^account_enseignement/$', views.account_enseignement, name="account_enseignement"),
    url(r'^create_basic_information/$', views.create_basic_information, name="create-basic-information"),
    url(r'^creation_chapitres/(?P<classeID>\w+)/$', views.creation_chapitres, name="creation-chapitres"),
    url(r'^creation_publier/(?P<classeID>\w+)/$', views.publierCours, name="creation-publier"),
    url(r'^creation_tds/(?P<classeID>\w+)/$', views.creation_tds, name="creation-tds"),
    url(r'^creation_examens/$', views.creation_examens, name="creation-examen"),
    url(r'^apprendre/(?P<idChapitre>\w+)/$', views.apprendre, name="apprendre-chapitre"),
    url(r'^apprendre/classe/(?P<idClass>\w+)/$', views.apprendre_classe, name="apprendre-classe"),
    url(r'^pdfview/$', views.pdfViewer, name="pdf-view"),
    url(r'^cours/intro/(?P<classeID>\w+)/$', views.cours_intro, name="cours-intro"),
    url(r'^cours/learn/(?P<classeID>\w+)/$', views.course_learn, name="cours-learn"),
    url(r'^cours/learn/enseignant/(?P<classeID>\w+)/$', views.course_learn_enseignant, name="cours-learn-enseignant"),
    url(r'^correction/$', views.corriger, name="corriger-test"),
    url(r'^demande/inscription/$', views.demande_inscription, name="demande-inscription-view"),
    url(r'^devoir/new/$', views.composerQuizz, name="devoir-new"),
    url(r'^devoir/faire/(?P<devoirID>\w+)/$', views.faireUnDevoir, name="devoir-faire"),
    url(r'^quiz/intro/(?P<devoirID>\w+)/$', views.quizz_intro, name="quiz-intro"),
    url(r'^paiement/finition/$', callback_wecashup_test, name='paiement-finition'),
    url(r'^paiement/webhook/$', webhook_wecashup_test, name='paiement-webhook'),
    url(r'^devoir/corriger/(?P<devoirID>\w+)/$', views.afficher_correction_devoir, name="devoir-corriger-profile"),
]